### PR TITLE
ElasticsearchIO template improvements

### LINKED ISSUE #388: Provide way to extract _id for indexed document in templates that write to Elasticsearch from index document fields
### Related Template(s)

BigQueryToElasticsearch

### What feature(s) are you requesting?

When using this template to index it auto-generates indexed document _id values.  This makes it difficult to be able to later update specific indexed documents.  It would be better if a field or function could be provided that extracts/computes a document _id from the fields of the document being indexed (Bigquery table/query-result row in the case of this template).

I see in the code for the ElasticsearchIO builder that there is a method `withIdFn` ([ElasticsearchIO.java line 1200](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java#L1200)) that suggests this seems relatively easily possible and just needs to be exposed via template parameters.

Perhaps just adding the `withIdFn` call to this [chain](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java#L93) 

and adding appropriate option to https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java

### LINKED ISSUE #408: [Bug]: ElasticsearchIO templates don't respect retry parameters in common scenario
### Related Template(s)

BigQueryToElasticsearch, GCSToElasticsearch, PubsubToElasticsearch

### What happened?

When running these templates against a busy Elasticsearch cluster it is common to encounter request timeout errors (because the busy ES cluster takes longer than 30s to respond to a request).  When this happens 4 times the job will be killed regardless of the elasticsearch retry parameters

### Beam Version

Newer than 2.35.0

### Relevant log output

```shell
First there will be logs like:
Error message from worker: java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE] org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:187) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:108) org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowReshuffleFn.processElement(BatchGroupAlsoByWindowReshuffleFn.java:56) org.apache.beam.runners.dataflow.worker.util.BatchGroupAlsoByWindowReshuffleFn.processElement(BatchGroupAlsoByWindowReshuffleFn.java:39) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:121) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:73) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:117) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:212) org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:163) org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:83) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:420) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:389) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:314) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:140) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:120) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:107) java.util.concurrent.FutureTask.run(FutureTask.java:266) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) java.lang.Thread.run(Thread.java:748) Caused by: org.apache.beam.sdk.util.UserCodeException: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE] org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39) com.google.cloud.teleport.v2.elasticsearch.utils.ElasticsearchIO$Write$WriteFn$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:228) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:187) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:340) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:268) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:84) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:416) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:404) com.google.cloud.teleport.v2.transforms.BigQueryConverters$TableRowToJsonFn.processElement(BigQueryConverters.java:198) com.google.cloud.teleport.v2.transforms.BigQueryConverters$TableRowToJsonFn$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:228) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:187) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:340) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:268) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:84) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:416) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:404) org.apache.beam.sdk.io.gcp.bigquery.PassThroughThenCleanup$IdentityFn.processElement(PassThroughThenCleanup.java:84) org.apache.beam.sdk.io.gcp.bigquery.PassThroughThenCleanup$IdentityFn$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:228) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:187) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:340) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:268) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:84) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:416) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:404) org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$TypedRead$3.processElement(BigQueryIO.java:1170) org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$TypedRead$3$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:228) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:184) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:340) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:268) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:84) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:416) org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output(DoFnOutputReceivers.java:76) org.apache.beam.sdk.transforms.MapElements$1.processElement(MapElements.java:142) org.apache.beam.sdk.transforms.MapElements$1$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:228) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:187) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:340) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:268) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:84) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:416) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:404) org.apache.beam.runners.dataflow.ReshuffleOverrideFactory$ReshuffleWithOnlyTrigger$1.processElement(ReshuffleOverrideFactory.java:86) org.apache.beam.runners.dataflow.ReshuffleOverrideFactory$ReshuffleWithOnlyTrigger$1$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:228) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:187) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:340) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:185) ... 21 more Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE] org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:834) org.elasticsearch.client.RestClient.performRequest(RestClient.java:259) org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) com.google.cloud.teleport.v2.elasticsearch.utils.ElasticsearchIO$Write$WriteFn.flushBatch(ElasticsearchIO.java:1507) com.google.cloud.teleport.v2.elasticsearch.utils.ElasticsearchIO$Write$WriteFn.processElement(ElasticsearchIO.java:1467) Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE] org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502) org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) java.lang.Thread.run(Thread.java:748)

Then when enough happen back-to-back to back the job is killed with a log like:
Workflow failed. Causes: S18:ReadFromBigQuery/ReadFromBigQueryWithQuery/Reshuffle.ViaRandomKey/Reshuffle/GroupByKey/Read+ReadFromBigQuery/ReadFromBigQueryWithQuery/Reshuffle.ViaRandomKey/Reshuffle/GroupByKey/GroupByWindow+ReadFromBigQuery/ReadFromBigQueryWithQuery/Reshuffle.ViaRandomKey/Reshuffle/ExpandIterable+ReadFromBigQuery/ReadFromBigQueryWithQuery/Reshuffle.ViaRandomKey/Values/Values/Map+ReadFromBigQuery/ReadFromBigQueryWithQuery/ReadFiles+ReadFromBigQuery/ReadFromBigQueryWithQuery/PassThroughThenCleanup/ParMultiDo(Identity)+TableRowsToJsonDocument+ReadFromBigQuery/ReadFromBigQueryWithQuery/PassThroughThenCleanup/View.AsIterable/ParDo(ToIsmRecordForGlobalWindow)+WriteToElasticsearch/WriteDocuments/ParDo(Write) failed., The job failed because a work item has failed 4 times. Look in previous log entries for the cause of each one of the 4 failures. For more information, see https://cloud.google.com/dataflow/docs/guides/common-errors. The work item was attempted on these workers: bigquery-to-elasticsearch-06160046-6l2z-harness-kfzc Root cause: Work item failed., bigquery-to-elasticsearch-06160046-6l2z-harness-kfzc Root cause: Work item failed., bigquery-to-elasticsearch-06160046-6l2z-harness-kfzc Root cause: Work item failed., bigquery-to-elasticsearch-06160046-6l2z-harness-kfzc Root cause: Work item failed.
```

### PR DESCRIPTION
**Pull request by ggprod**
switch create to index to allow duplicates (due to timeout/retry) to not cause errors + add javascript functions for extraction of id, index, type, and whether or not to delete (already supported by ElasticsearchIO)

Resolves #388 
Resolves #408

### CODE REVIEW

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java [hunk 1]
```diff
@@ -95,6 +96,42 @@ public PDone expand(PCollection<String> jsonStrings) {
...
             .withMaxBatchSizeBytes(options().getBatchSizeBytes());
+    
+    if (options().getJavascriptIdFnGcsPath() != null && options().getJavascriptIdFnName() != null){
+      ValueExtractorFn idFn = ValueExtractorFn.newBuilder()
+      .setFileSystemPath(options().getJavascriptIdFnGcsPath())
+      .setFunctionName(options().getJavascriptIdFnName())
+      .build();
+
+      elasticsearchWriter.withIdFn(idFn);
+    }
```
Comment (bvolpato) [inline v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java:107]: Did you run spotless:apply? The indent seems off

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java [hunk 2]
```diff
@@ -1452,7 +1452,8 @@ public void processElement(ProcessContext context) throws Exception {
                     "{ \"update\" : %s }%n{ \"doc\" : %s, \"doc_as_upsert\" : true }%n",
                     documentMetadata, document));
           } else {
-            batch.add(String.format("{ \"create\" : %s }%n%s%n", documentMetadata, document));
+            // switch from create to index to allow upsert (beneficial in case of duplication due to timeout/retry)
+            batch.add(String.format("{ \"index\" : %s }%n%s%n", documentMetadata, document));
```
Comment (bvolpato) [inline v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1456]: Makes sense. This matches https://github.com/apache/beam/blob/master/sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java#L1576

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java (hunk 1 above)
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/WriteToElasticsearch.java:107]: yes, it looks like I forgot but I ran it now and checked in the changes

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java (hunk 2 above)
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1456]: is a change necessary or can I resolve this?

**Comment by alexandregiordanelli** [comment]
can someone approve it asap? I really need this change.

**Review by alexandregiordanelli — APPROVED** [review]

**Review by alexandregiordanelli — APPROVED** [review]

File: src/test/java/com/google/cloud/teleport/splunk/CustomX509TrustManagerTest.java [hunk 3]
```diff
@@ -47,13 +47,11 @@ public void setUp()
         new FileInputStream(classLoader.getResource("PubsubToSplunkTestData/RootCA.crt").getFile());
     FileInputStream recognizedInputStream =
         new FileInputStream(
-            classLoader
-                .getResource("PubsubToSplunkTestData/RootCASignedCertificate.crt")
-                .getFile());
```
Comment (an2x) [inline src/test/java/com/google/cloud/teleport/splunk/CustomX509TrustManagerTest.java:52]: It seems that the PR includes changes merged from the main branch.
And [ggprod:elasticsearch-io-improvements](https://github.com/ggprod/DataflowTemplates/tree/elasticsearch-io-improvements) branch is also behind `main`.
Can you please **rebase** the branch onto master? (**merge** won't work as our CLA check won't accept commits made by `cloud-teleport` in your PR).

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java [hunk 4]
```diff
@@ -1513,21 +1541,31 @@ private HttpEntity handleRetry(
...
         int attempt = 0;
         // while retry policy exists
         while (BackOffUtils.next(sleeper, backoff)) {
-          LOG.warn(String.format(RETRY_ATTEMPT_LOG, ++attempt));
-          Request request = new Request(method, endpoint);
-          request.addParameters(params);
-          request.setEntity(requestBody);
-          response = restClient.performRequest(request);
-          responseEntity = new BufferedHttpEntity(response.getEntity());
+          LOG.warn(RETRY_ATTEMPT_LOG, ++attempt);
```
Comment (an2x) [inline v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1550]: I think removing String.format won't work, because `RETRY_ATTEMPT_LOG` has `%d` in the message as the placeholder, and `LOG.warn` expects `{ }` as the placeholder.

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java [hunk 5]
```diff
@@ -1452,7 +1455,9 @@ public void processElement(ProcessContext context) throws Exception {
                     "{ \"update\" : %s }%n{ \"doc\" : %s, \"doc_as_upsert\" : true }%n",
                     documentMetadata, document));
           } else {
-            batch.add(String.format("{ \"create\" : %s }%n%s%n", documentMetadata, document));
+            // switch from create to index to allow upsert (beneficial in case of duplication due to
+            // timeout/retry)
+            batch.add(String.format("{ \"index\" : %s }%n%s%n", documentMetadata, document));
```
Comment (an2x) [inline v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1460]: Not sure about this change. This may be a breaking change. I image some template users may want it to fail if the target document already exists (e.g. they only move incremental changes to Elastic, not expecting any duplicates, and if there are any that's a configuration problem).
Maybe add a parameter to keep "create" as the default and switch to "index" only if the parameter is set?

**Review by an2x — CHANGES_REQUESTED** [review]

File: src/test/java/com/google/cloud/teleport/splunk/CustomX509TrustManagerTest.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (ggprod) [reply src/test/java/com/google/cloud/teleport/splunk/CustomX509TrustManagerTest.java:52]: I think something has gotten really messed up with this PR.. This difference doesn't actually exist when I compare the file on the branch ggprod:elasticsearch-io-improvements vs GoogleCloudPlatform:main.  The files are actually identical (see links to the two files below).

see: 
https://github.com/ggprod/DataflowTemplates/blob/elasticsearch-io-improvements/src/test/java/com/google/cloud/teleport/splunk/CustomX509TrustManagerTest.java

vs

https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/src/test/java/com/google/cloud/teleport/splunk/CustomX509TrustManagerTest.java

Not sure how that happened (perhaps a strange github bug) or how to fix it

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ValueExtractorTransform.java [hunk 6]
```diff
@@ -68,11 +72,13 @@ public String apply(JsonNode input) {
             "Both function name and file system path need to be set.");
       }
 
-      JavascriptRuntime runtime =
+      if (runtime == null) {
```
[the remark this answers is not in the document]
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ValueExtractorTransform.java:75]: unfortunately this is not actually a DoFn.. it is a sub-class of a SerializableFunction

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ValueExtractorTransform.java [hunk 7]
```diff
@@ -91,4 +97,65 @@ public abstract static class Builder {
...
+   * BooleanValueExtractorFn#apply(JsonNode)} will return null if {@link
+   * BooleanValueExtractorFn#functionName()} and {@link BooleanValueExtractorFn#fileSystemPath()}
+   * are null meaning no function is applied to the document.
+   *
+   * <p>If only one of {@link BooleanValueExtractorFn#functionName()} or {@link
+   * BooleanValueExtractorFn#fileSystemPath()} are null then {@link
+   * com.google.api.gax.rpc.InvalidArgumentException} is thrown.
+   */
+  @AutoValue
+  public abstract static class BooleanValueExtractorFn implements BooleanFieldValueExtractFn {
```
[the remark this answers is not in the document]
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/transforms/ValueExtractorTransform.java:112]: Yes, agreed, a bit messy, though it is based on this:
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java#L1101

vs

https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java#L1104

File: v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md [hunk 8]
```diff
@@ -50,7 +50,7 @@ mvn clean package \
     -Dbase-container-image.version=${BASE_CONTAINER_IMAGE_VERSION} \
     -Dapp-root=${APP_ROOT} \
     -Dcommand-spec=${COMMAND_SPEC} \
-    -am -pl ${TEMPLATE_MODULE}
+    -am -pl googlecloud-to-elasticsearch
```
[the remark this answers is not in the document]
Comment (ggprod) [reply v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md:53]: because the build will not work unless it is googlecloud-to-elasticsearch.. that is the project name in the POM file

File: v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md [hunk 9]
```diff
@@ -139,6 +139,69 @@ echo '{
               "helpText":"Max retry duration in milliseconds, must be > 0. Default: no retries",
               "paramType":"TEXT",
               "isOptional":true
+          },
+          {
+              "name":"javascriptIndexFnGcsPath",
+              "label":"Gcs path to javascript udf source for function to extract index name from row",
```
[the remark this answers is not in the document]
Comment (ggprod) [reply v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md:145]: sure, will update accordingly

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java (hunk 5 above)
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1460]: sure, I can do that.. though in the original ElasticsearchIO (in the beam repo) it uses index rather than create

Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1460]: see: https://github.com/apache/beam/blob/master/sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java#L1576

Out of curiosity, why does this repo define its own ElasticsearchIO which is quite different?

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java (hunk 4 above)
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1550]: sure, I had copied this from the beam version of ElasticsearchIO here: https://github.com/apache/beam/blob/master/sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java#L2547

I did that to make retry work properly as it looked like the logic in the beam ElasticsearchIO had functional retries whereas this version did not (at least not in conventional failure cases that would throw exceptions)

But yes, I can definitely add back the String.format

File: src/test/java/com/google/cloud/teleport/splunk/CustomX509TrustManagerTest.java [hunk 10]
```diff
@@ -47,13 +47,11 @@ public void setUp()
...
+            classLoader.getResource("PubsubToSplunkTestData/RecognizedCertificate.crt").getFile());
     FileInputStream unrecognizedInputStream =
         new FileInputStream(
             classLoader
-                .getResource("PubsubToSplunkTestData/UnrecognizedSelfSignedCertificate.crt")
```
Comment (ggprod) [inline src/test/java/com/google/cloud/teleport/splunk/CustomX509TrustManagerTest.java:56]: again if you compare the latest versions of the branches they both look like the right, so github is showing a non-existent change here

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java (hunk 4 above)
Comment (an2x) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1550]: Note that the Beam version has a proper `RETRY_ATTEMPT_LOG` message (with `{}`, not `%d`):
https://github.com/apache/beam/blob/bf39489b2a1fd45e6798483d083e4ad240f66891/sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java#L1981
So either use String.format with a `%d` message or direct logging with a `{}` message.

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java (hunk 5 above)
Comment (an2x) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java:1460]: I think the only reason this repo has its own version is that at the time the template was created ElasticsearchIO wasn't released as part of Beam yet.
So `ElasticsearchIO` was simply copy-pasted from there.

Unfortunately now these two versions diverged a lot, so we need to do something about it, but I don't have a specific plan for now :) Ideally, we need to merge all changes from both repos into the Beam's repo, and make the template re-use `ElasticseachIO` from Beam SDK.

File: v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md (hunk 8 above)
[the remark this answers is not in the document]
Comment (ggprod) [reply v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md:53]: It has to be one of the projects from the associated [POM](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/v2/pom.xml#L672)

or am I missing something?

[the remark this answers is not in the document]
Comment (an2x) [reply v2/googlecloud-to-elasticsearch/docs/BigQueryToElasticsearch/README.md:53]: Sorry, googlecloud-to-elasticsearch is correct. I thought TEMPLATE_MODULE was the same thing but in fact it's **bigquery**-to-elasticsearch.

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java [hunk 11]
```diff
@@ -73,4 +73,64 @@ public interface ElasticsearchWriteOptions extends PipelineOptions {
...
+
+  @Description("Whether to use partial updates (update type) with Elasticsearch requests")
+  Boolean getUsePartialUpdate();
+
+  void setUsePartialUpdate(Boolean usePartialUpdate);
+
+  @Description("Whether to use index (supports upsert) rather than create (errors on duplicate _id) in bulk requests")
+  Boolean getUseBulkIndexRatherThanCreate();
+
+  void setUseBulkIndexRatherThanCreate(Boolean useBulkIndexRatherThanCreate);
```
Comment (an2x) [inline v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java:135]: nit: Maybe make it an Enum-type parameter called "bulkInsertMethod" or something like this, with CREATE and INDEX possible values, CREATE being the default?

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java [hunk 12]
```diff
@@ -73,4 +73,64 @@ public interface ElasticsearchWriteOptions extends PipelineOptions {
   Long getMaxRetryDuration();
 
   void setMaxRetryDuration(Long maxRetryDuration);
+
+  @Description("A property in the document being indexed whose value specifies which index to add the doc to (takes precendence over an index UDF)")
+  String getPropertyAsIndex();
+
+  void setPropertyAsIndex(String propertyAsIndex);
+
+  @Description("GCS path to JavaScript udf source for index extraction function")
```
Comment (an2x) [inline v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java:82]: UDF is still spelled "udf" in a few places.

**Review by an2x — CHANGES_REQUESTED** [review]

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java (hunk 5 above)
Comment (bvolpato) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java]: Agree with @ggprod that using `index` is safer, considering that we may not have exactly-once guarantees.

But also +1 on @an2x on not carrying a forked version. I glanced over ElasticsearchIO here, and apparently, it doesn't seem that we would need to merge anything upstream, but it needs some further verification/tests.

Digging further, https://github.com/GoogleCloudPlatform/DataflowTemplates/commit/302d261e7256b448c47eb7daf093903d0a46acf1 has some explanations and mentions that it was a temporary solution:

```
/**
 * This class was included and changed as a temporary solution to cover Elasticsearch's requirement
 * of op_type for data streams. The required feature will be available with Apache Beam 2.33.0.
 * After migrating to Apache Beam 2.33.0 this class should be removed.
 * Jira ticket: <a href="https://issues.apache.org/jira/browse/BEAM-12601">Support append-only indices in ES output</a>.
 * Github pull request: <a href="https://github.com/apache/beam/pull/15257">[BEAM-12601] Add append-only option</a>.
 */
```

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java (hunk 12 above)
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java]: I believe I've updated all instances to UDF, are there still any left?

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java (hunk 11 above)
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java]: made the recommended change, look ok?

File: v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java [hunk 13]
```diff
@@ -73,4 +73,49 @@ public interface ElasticsearchWriteOptions extends PipelineOptions {
   Long getMaxRetryDuration();
 
   void setMaxRetryDuration(Long maxRetryDuration);
+
+  @Description("Gcs path to javascript udf source for index extraction function")
```
[the remark this answers is not in the document]
Comment (ggprod) [reply v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/options/ElasticsearchWriteOptions.java]: ok, I believe I addressed these points (to address 3, I updated the descriptions of the new parameters to make it more clear and descriptive),  look ok?

**Review by an2x — DISMISSED** [review]

**Comment by ggprod** [comment]
@an2x thanks Nick for the review and approval!  I noticed the 2 failed checks but they both seem to be based on code in the main branch that hasn't changed as part of this PR.  Will the prevent merging of this PR?

**Comment by an2x** [comment]
>

**Comment by an2x** [comment]
> @an2x thanks Nick for the review and approval! I noticed the 2 failed checks but they both seem to be based on code in the main branch that hasn't changed as part of this PR. Will the prevent merging of this PR?

No, it won't.

**Comment by bvolpato** [comment]
@ggprod Sounds like `mvn spotless:apply` should fix the validation for ValueExtractorTransform.java. Did you give it a try?

**Comment by ggprod** [comment]
> @ggprod Sounds like `mvn spotless:apply` should fix the validation for ValueExtractorTransform.java. Did you give it a try?

I don't believe there were any spotless problems with ValueExtractorTransform.java.  Did you see some somewhere?  I did run mvn spotless:apply but found it fixed many issues in other files on the main branch that weren't touched by me

**Comment by bvolpato** [comment]
> > @ggprod Sounds like `mvn spotless:apply` should fix the validation for ValueExtractorTransform.java. Did you give it a try?
> 
> I don't believe there were any spotless problems with ValueExtractorTransform.java. Did you see some somewhere? I did run mvn spotless:apply but found it fixed many issues in other files on the main branch that weren't touched by me

You got to do it within the v2 module, or if you are in the root: `mvn spotless:apply -f v2`. v2 is not currently a module from the parent project

**Comment by ggprod** [comment]
@an2x apologies Nick, I had just noticed today there was a minor issue with the README.md files for the Bigquery and GCS Elasticsearch templates so made a small commit to fix those (adding the apiKey to the list of required parameters and updating the Bigquery template to make the table parameter optional, since it could be replaced with the query parameter)

**Comment by ggprod** [comment]
> > > @ggprod Sounds like `mvn spotless:apply` should fix the validation for ValueExtractorTransform.java. Did you give it a try?
> > 
> > 
> > I don't believe there were any spotless problems with ValueExtractorTransform.java. Did you see some somewhere? I did run mvn spotless:apply but found it fixed many issues in other files on the main branch that weren't touched by me
> 
> You got to do it within the v2 module, or if you are in the root: `mvn spotless:apply -f v2`. v2 is not currently a module from the parent project

@bvolpato Ok, I ran spotless:apply in the v2 folder.  Most of the changes were for files not touced as part of this PR and I did not commit those changes but discarded them.  There were a few minor updates to some of the files modified in this PR and I kept and committed those (most recent commit)

**Review by an2x — APPROVED** [review]
