### PR TITLE
Issue 582 - MongoDBtoBigQuery with UDF: ScriptObjectMirror cannot be cast to bson.Document

### LINKED ISSUE #582: [Bug]: MongoDBtoBigQuery with UDF: ScriptObjectMirror cannot be cast to bson.Document
### Related Template(s)

MongoDB to BigQuery

### What happened?

When creating a job with MongoDB to BigQuery template and specify a UDF javascript file and function, the job fails to start. See relevant logs below.

When UDF file and function are not specified, jobs with the same template can run normally.

### Beam Version

Newer than 2.43.0

### Relevant log output

```shell
com.google.cloud.teleport.v2.common.UncaughtExceptionLogger - The template launch failed.
java.lang.ClassCastException: class org.openjdk.nashorn.api.scripting.ScriptObjectMirror cannot be cast to class org.bson.Document (org.openjdk.nashorn.api.scripting.ScriptObjectMirror and org.bson.Document are in unnamed module of loader 'app')
	at com.google.cloud.teleport.v2.mongodb.templates.MongoDbUtils.getTableFieldSchemaForUDF(MongoDbUtils.java:167)
	at com.google.cloud.teleport.v2.mongodb.templates.MongoDbToBigQuery.run(MongoDbToBigQuery.java:95)
	at com.google.cloud.teleport.v2.mongodb.templates.MongoDbToBigQuery.main(MongoDbToBigQuery.java:82)
```

### PR DESCRIPTION
**Pull request by Polber**
This PR fixes #582 by correcting illegal cast to bson.Document in MongoDB templates that utilize UDF's.

Signed-off-by: Jeffrey Kinard <jeff@thekinards.com>

### CODE REVIEW

File: v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java [hunk 1]
```diff
@@ -152,6 +153,11 @@ public void testMongoDbToBigQuery() throws IOException {
     List<Document> mongoDocuments = generateDocuments();
     mongoDbClient.insertDocuments(collectionName, mongoDocuments);
 
+    String udfFileName = "transform.js";
+    artifactClient.uploadArtifact(
+        "input/" + udfFileName,
+        Resources.getResource("MongoDbToBigQuery/" + udfFileName).getPath());
```
Comment (bvolpato) [inline v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java:159]: This looks good.

A nit but it might be preference.
I recently changed a few tests to use:

```suggestion
    String udfFileName = "transform.js";
    artifactClient.createArtifact(
        "input/" + udfFileName,
        "function transform(inJson) {\n"
            + "    var outJson = JSON.parse(inJson);\n"
            + "    outJson.udf = \"out\";\n"
            + "    return JSON.stringify(outJson);\n"
            + "}");
```


IMHO test is more readable / self-contained, so easier to digest.

**Review by bvolpato — DISMISSED** [review]
LGTM. Added a suggestion but feel free to skip

(BTW Spotless check is failing, please `mvn spotless:apply`)

File: v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java (hunk 1 above)
Comment (Polber) [reply v2/mongodb-to-googlecloud/src/test/java/com/google/cloud/teleport/v2/mongodb/templates/MongoDbToBigQueryIT.java]: I like that better. Fixed.

**Comment by theshanbhag** [comment]
Hi @Polber @bvolpato can we please merge this?

**Review by bvolpato — DISMISSED** [review]
